version: "2"
run:
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - goconst
    - godot
    - lll
    - misspell
    - promlinter
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
        - fmt.Fprintln
        - fmt.Fprint
    goconst:
      min-occurrences: 5
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/pedro-stanaka/prom-scrape-analyzer)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
